import type { CatProfile, Conversation, Post, Story } from '@/types'

export const CURRENT_USER_ID = 'cat-luna'

export const mockProfiles: CatProfile[] = [
  {
    id: CURRENT_USER_ID,
    name: 'Luna',
    breed: 'British Shorthair',
    age: 3,
    bio: 'Napping professional. Part-time window supervisor. Full-time soft.',
    avatar: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=400&fit=crop',
    followers: 128,
    following: 42,
    postsCount: 12,
  },
  {
    id: 'cat-milo',
    name: 'Milo',
    breed: 'Orange Tabby',
    age: 2,
    bio: 'Chaos coordinator. Will trade cuddles for tuna.',
    avatar: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop',
    followers: 210,
    following: 67,
    postsCount: 28,
  },
  {
    id: 'cat-olive',
    name: 'Olive',
    breed: 'Siamese',
    age: 4,
    bio: 'Elegant opinions. Soft paws. Strong meows.',
    avatar: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=400&h=400&fit=crop',
    followers: 340,
    following: 89,
    postsCount: 45,
  },
  {
    id: 'cat-bean',
    name: 'Bean',
    breed: 'Scottish Fold',
    age: 1,
    bio: 'Tiny but mighty. Currently learning gravity.',
    avatar: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=400&h=400&fit=crop',
    followers: 96,
    following: 31,
    postsCount: 8,
  },
  {
    id: 'cat-pepper',
    name: 'Pepper',
    breed: 'Maine Coon',
    age: 5,
    bio: 'Fluff ambassador. Sunbeam collector.',
    avatar: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=400&h=400&fit=crop',
    followers: 512,
    following: 120,
    postsCount: 67,
  },
]

export const mockStories: Story[] = [
  {
    id: 'story-1',
    authorId: 'cat-milo',
    authorName: 'Milo',
    authorAvatar: mockProfiles[1].avatar,
    viewed: false,
  },
  {
    id: 'story-2',
    authorId: 'cat-olive',
    authorName: 'Olive',
    authorAvatar: mockProfiles[2].avatar,
    viewed: false,
  },
  {
    id: 'story-3',
    authorId: 'cat-bean',
    authorName: 'Bean',
    authorAvatar: mockProfiles[3].avatar,
    viewed: true,
  },
  {
    id: 'story-4',
    authorId: 'cat-pepper',
    authorName: 'Pepper',
    authorAvatar: mockProfiles[4].avatar,
    viewed: false,
  },
]

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    authorId: 'cat-milo',
    authorName: 'Milo',
    authorAvatar: mockProfiles[1].avatar,
    image: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=900&h=900&fit=crop',
    caption: 'Caught mid-zoomies. Form is temporary, chaos is forever.',
    tags: ['#catlife', '#zoomies', '#orangecat'],
    likes: 184,
    likedByMe: false,
    createdAt: '2026-07-19T08:30:00.000Z',
    comments: [
      {
        id: 'c-1',
        authorId: 'cat-olive',
        authorName: 'Olive',
        authorAvatar: mockProfiles[2].avatar,
        text: 'Iconic energy. Respect.',
        createdAt: '2026-07-19T09:00:00.000Z',
      },
    ],
  },
  {
    id: 'post-2',
    authorId: 'cat-olive',
    authorName: 'Olive',
    authorAvatar: mockProfiles[2].avatar,
    image: 'https://images.unsplash.com/photo-1494256997604-768d1f608cac?w=900&h=900&fit=crop',
    caption: 'Morning light hits different when you own the windowsill.',
    tags: ['#softlife', '#siamese', '#sunbeam'],
    likes: 256,
    likedByMe: true,
    createdAt: '2026-07-18T16:15:00.000Z',
    comments: [
      {
        id: 'c-2',
        authorId: CURRENT_USER_ID,
        authorName: 'Luna',
        authorAvatar: mockProfiles[0].avatar,
        text: 'This lighting is purrfection.',
        createdAt: '2026-07-18T17:00:00.000Z',
      },
      {
        id: 'c-3',
        authorId: 'cat-pepper',
        authorName: 'Pepper',
        authorAvatar: mockProfiles[4].avatar,
        text: 'Teaching a masterclass in lounging.',
        createdAt: '2026-07-18T18:22:00.000Z',
      },
    ],
  },
  {
    id: 'post-3',
    authorId: 'cat-bean',
    authorName: 'Bean',
    authorAvatar: mockProfiles[3].avatar,
    image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=900&h=900&fit=crop',
    caption: 'First cardboard box of the day. Reviews: 10/10 would sit again.',
    tags: ['#kitten', '#boxlife', '#catlife'],
    likes: 98,
    likedByMe: false,
    createdAt: '2026-07-18T11:45:00.000Z',
    comments: [],
  },
  {
    id: 'post-4',
    authorId: 'cat-pepper',
    authorName: 'Pepper',
    authorAvatar: mockProfiles[4].avatar,
    image: 'https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?w=900&h=900&fit=crop',
    caption: 'Fluff levels: maximum. Treat levels: negotiate.',
    tags: ['#mainecoon', '#fluff', '#treats'],
    likes: 412,
    likedByMe: false,
    createdAt: '2026-07-17T20:10:00.000Z',
    comments: [
      {
        id: 'c-4',
        authorId: 'cat-milo',
        authorName: 'Milo',
        authorAvatar: mockProfiles[1].avatar,
        text: 'The mane is unreal.',
        createdAt: '2026-07-17T21:00:00.000Z',
      },
    ],
  },
  {
    id: 'post-5',
    authorId: CURRENT_USER_ID,
    authorName: 'Luna',
    authorAvatar: mockProfiles[0].avatar,
    image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=900&h=900&fit=crop',
    caption: 'Supervising from the high shelf. Everything is under control.',
    tags: ['#britishshorthair', '#vibes', '#catlife'],
    likes: 167,
    likedByMe: false,
    createdAt: '2026-07-16T14:00:00.000Z',
    comments: [],
  },
]

export const mockConversations: Conversation[] = [
  {
    id: 'chat-1',
    participantId: 'cat-milo',
    participantName: 'Milo',
    participantAvatar: mockProfiles[1].avatar,
    lastMessage: 'Race you to the treat jar?',
    updatedAt: '2026-07-19T10:12:00.000Z',
    unread: 2,
    messages: [
      {
        id: 'm-1',
        senderId: 'cat-milo',
        text: 'Did you see the new cardboard fortress?',
        createdAt: '2026-07-19T09:40:00.000Z',
      },
      {
        id: 'm-2',
        senderId: CURRENT_USER_ID,
        text: 'Obviously. I claimed the top floor.',
        createdAt: '2026-07-19T09:55:00.000Z',
      },
      {
        id: 'm-3',
        senderId: 'cat-milo',
        text: 'Race you to the treat jar?',
        createdAt: '2026-07-19T10:12:00.000Z',
      },
    ],
  },
  {
    id: 'chat-2',
    participantId: 'cat-olive',
    participantName: 'Olive',
    participantAvatar: mockProfiles[2].avatar,
    lastMessage: 'Sunbeam meetup at 3?',
    updatedAt: '2026-07-18T15:30:00.000Z',
    unread: 0,
    messages: [
      {
        id: 'm-4',
        senderId: CURRENT_USER_ID,
        text: 'Your windowsill post was elite.',
        createdAt: '2026-07-18T14:10:00.000Z',
      },
      {
        id: 'm-5',
        senderId: 'cat-olive',
        text: 'Sunbeam meetup at 3?',
        createdAt: '2026-07-18T15:30:00.000Z',
      },
    ],
  },
  {
    id: 'chat-3',
    participantId: 'cat-pepper',
    participantName: 'Pepper',
    participantAvatar: mockProfiles[4].avatar,
    lastMessage: 'Bring the feather wand next time.',
    updatedAt: '2026-07-17T19:05:00.000Z',
    unread: 1,
    messages: [
      {
        id: 'm-6',
        senderId: 'cat-pepper',
        text: 'Bring the feather wand next time.',
        createdAt: '2026-07-17T19:05:00.000Z',
      },
    ],
  },
]
